#!/usr/bin/env node

import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const VERSION_FILES = [
  'crates/modbussim-app/Cargo.toml',
  'crates/modbussim-app/tauri.conf.json',
  'crates/modbusmaster-app/Cargo.toml',
  'crates/modbusmaster-app/tauri.conf.json',
]

const CATEGORY_ORDER = ['Added', 'Fixed', 'Changed', 'Documentation', 'Tests']
const CATEGORY_TITLES = {
  Added: 'Added 新增',
  Fixed: 'Fixed 修复',
  Changed: 'Changed 改进',
  Documentation: 'Documentation 文档',
  Tests: 'Tests 测试',
}

export function normalizeVersion(value) {
  const match = String(value).trim().match(/^v?(\d+)\.(\d+)\.(\d+)$/)
  if (!match) throw new Error(`expected a stable SemVer tag, got: ${value}`)
  return `${Number(match[1])}.${Number(match[2])}.${Number(match[3])}`
}

export function nextPatchVersion(tag) {
  const version = normalizeVersion(tag)
  const [major, minor, patch] = version.split('.').map(Number)
  return `${major}.${minor}.${patch + 1}`
}

export function parseCommit(subject) {
  const conventional = subject.match(
    /^(feat|fix|perf|refactor|docs|test|build|ci|chore)(?:\(([^)]+)\))?(!)?:\s*(.+)$/i,
  )
  if (!conventional) return { category: 'Changed', summary: subject }

  const [, rawType, scope, breaking, summary] = conventional
  const type = rawType.toLowerCase()
  let category = 'Changed'
  if (type === 'feat') category = 'Added'
  else if (type === 'fix') category = 'Fixed'
  else if (type === 'docs') category = 'Documentation'
  else if (type === 'test') category = 'Tests'

  const scopedSummary = scope ? `${scope}: ${summary}` : summary
  return {
    category,
    summary: breaking ? `${scopedSummary} (breaking)` : scopedSummary,
  }
}

export function groupCommits(subjects) {
  const groups = new Map(CATEGORY_ORDER.map((category) => [category, []]))
  for (const subject of subjects.map((item) => item.trim()).filter(Boolean)) {
    const commit = parseCommit(subject)
    groups.get(commit.category).push(commit.summary)
  }
  return groups
}

export function buildChangelogSection(version, date, subjects) {
  const groups = groupCommits(subjects)
  const lines = [`## [${normalizeVersion(version)}] - ${date}`, '']

  for (const category of CATEGORY_ORDER) {
    const entries = groups.get(category)
    if (entries.length === 0) continue
    lines.push(`### ${CATEGORY_TITLES[category]}`, '')
    lines.push(...entries.map((entry) => `- ${entry}`), '')
  }

  lines.push(
    '### Notes 说明',
    '',
    '- 本节由夜间发布自动化根据上一版本后的提交生成;合并发布 PR 前可直接编辑补充 / This section is generated by the nightly release automation from commits since the previous version and can be refined before the release PR is merged.',
    '',
  )
  return lines.join('\n')
}

export function updateCargoToml(source, version) {
  const updated = source.replace(
    /(\[package\][\s\S]*?\nversion = ")[^"]+("\n)/,
    `$1${normalizeVersion(version)}$2`,
  )
  if (updated === source) throw new Error('could not update Cargo.toml package version')
  return updated
}

export function updateJsonVersion(source, version) {
  const updated = source.replace(
    /("version"\s*:\s*")[^"]+("\s*,)/,
    `$1${normalizeVersion(version)}$2`,
  )
  if (updated === source) throw new Error('could not update JSON version')
  return updated
}

export function prependChangelog(source, section) {
  const firstRelease = source.indexOf('\n## [')
  if (firstRelease < 0) throw new Error('could not find the first CHANGELOG release section')
  const heading = section.split('\n', 1)[0]
  if (source.includes(`${heading}\n`)) throw new Error(`${heading} already exists in CHANGELOG.md`)
  const introduction = source.slice(0, firstRelease).trimEnd()
  const history = source.slice(firstRelease).trimStart()
  return `${introduction}\n\n${section.trim()}\n\n${history}`
}

function read(root, path) {
  return readFileSync(resolve(root, path), 'utf8')
}

function write(root, path, value) {
  writeFileSync(resolve(root, path), value)
}

export function currentVersion(root = process.cwd()) {
  const match = read(root, VERSION_FILES[0]).match(/\nversion = "([^"]+)"/)
  if (!match) throw new Error(`could not read version from ${VERSION_FILES[0]}`)
  return normalizeVersion(match[1])
}

export function verifyPreparedRelease(root, tag) {
  const version = normalizeVersion(tag)
  const errors = []

  for (const path of VERSION_FILES) {
    const source = read(root, path)
    const match = path.endsWith('.json')
      ? source.match(/"version"\s*:\s*"([^"]+)"/)
      : source.match(/\nversion = "([^"]+)"/)
    if (!match || match[1] !== version) errors.push(`${path} is not version ${version}`)
  }

  if (!read(root, 'CHANGELOG.md').includes(`## [${version}]`)) {
    errors.push(`CHANGELOG.md has no ${version} section`)
  }

  if (errors.length > 0) throw new Error(errors.join('\n'))
  return version
}

export function prepareRelease(root, { fromTag, version, date, subjects }) {
  const baseVersion = normalizeVersion(fromTag)
  const nextVersion = normalizeVersion(version)
  if (currentVersion(root) !== baseVersion) {
    throw new Error(`app version must match latest tag ${fromTag} before preparing a release`)
  }
  if (nextVersion !== nextPatchVersion(fromTag)) {
    throw new Error(`expected next patch ${nextPatchVersion(fromTag)}, got ${nextVersion}`)
  }
  if (subjects.length === 0) throw new Error(`no commits found after ${fromTag}`)

  for (const path of VERSION_FILES) {
    const source = read(root, path)
    write(root, path, path.endsWith('.json')
      ? updateJsonVersion(source, nextVersion)
      : updateCargoToml(source, nextVersion))
  }
  const section = buildChangelogSection(nextVersion, date, subjects)
  write(root, 'CHANGELOG.md', prependChangelog(read(root, 'CHANGELOG.md'), section))

  verifyPreparedRelease(root, `v${nextVersion}`)
}

function option(args, name) {
  const index = args.indexOf(name)
  if (index < 0 || !args[index + 1]) throw new Error(`missing ${name}`)
  return args[index + 1]
}

function gitSubjects(fromTag) {
  const output = execFileSync(
    'git',
    ['log', '--reverse', '--format=%s', `${fromTag}..HEAD`],
    { encoding: 'utf8' },
  )
  return output.split('\n').map((line) => line.trim()).filter(Boolean)
}

function main(args) {
  const [command, ...rest] = args
  if (command === 'next') {
    if (!rest[0]) throw new Error('usage: prepare-release.mjs next <tag>')
    console.log(nextPatchVersion(rest[0]))
    return
  }
  if (command === 'current') {
    console.log(currentVersion())
    return
  }
  if (command === 'verify') {
    if (!rest[0]) throw new Error('usage: prepare-release.mjs verify <tag>')
    console.log(`release v${verifyPreparedRelease(process.cwd(), rest[0])} is internally consistent`)
    return
  }
  if (command === 'verify-current') {
    const version = currentVersion()
    console.log(`release v${verifyPreparedRelease(process.cwd(), version)} is internally consistent`)
    return
  }
  if (command === 'prepare') {
    const fromTag = option(rest, '--from')
    const version = option(rest, '--version')
    const date = option(rest, '--date')
    const subjects = gitSubjects(fromTag)
    prepareRelease(process.cwd(), { fromTag, version, date, subjects })
    console.log(`prepared v${normalizeVersion(version)} from ${subjects.length} commit(s) after ${fromTag}`)
    return
  }
  throw new Error('usage: prepare-release.mjs <next|current|verify|verify-current|prepare> ...')
}

if (import.meta.url === `file://${process.argv[1]}`) {
  try {
    main(process.argv.slice(2))
  } catch (error) {
    console.error(error instanceof Error ? error.message : error)
    process.exit(1)
  }
}
